disable-snowgrow: false
disable-drops: false
log-animals: false
block-caps: true
remove-on-exit: false
safe-boats: true
safe-boats-delay: 6000
safe-boats-drop: true
safe-minecarts: true
safe-minecarts-delay: 6000
safe-minecarts-drop: true
disabled-items:
    left-click:
    right-click:
    - 261
    - 332
    - 344
    - 346
    - 381
    - 383

