disable-snowgrow: false
disable-drops: false
log-animals: false
block-caps: true
safe-boats: true
safe-boats-drop: true
safe-minecarts: true
safe-minecarts-drop: true
disabled-items:
    left-click:
    right-click:
    - 261
    - 332
    - 344
    - 346
    - 381
    - 383

