disable-snowgrow: false
disable-drops: true
log-animals: false
block-caps: true
safe-boats: true
safe-minecarts: true
disabled-items:
    left-click:
    right-click:
    - 261
    - 332
    - 344
    - 346
    - 381
    - 383

