name: KitchenSink
version: 0.1
author: Travis Watkins
main: nu.nerd.kitchensink.KitchenSink
softdepend: [WorldGuard]
description: 

commands:
    lag:
        description: Get current TPS and memory stats
